# This is a basic workflow to help you get started with Actions

name: Test and Publish to PSGallery

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  RunPesterTests:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Run Pester Tests
        if: github.event_name == 'pull_request' || 'workflow_dispatch'
        run: |
          Get-ChildItem -Path .\src\modules\ -Directory | ForEach-Object {
            $ModuleName = $_.Name
            Write-Output "Running Pester Tests for $ModuleName"
            Write-Output "Running Pester Tests for Public Functions"
            Invoke-Pester -Path ".\src\modules\$ModuleName\Public"
            Write-Output "Running Pester Tests for Private Functions"
            Invoke-Pester -Path ".\src\modules\$ModuleName\Private"
          }
