name: Test and Publish to PSGallery

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/modules/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/modules/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  SetUp:
    runs-on: windows-latest
    outputs:
      module_directories: ${{ steps.modulepaths.outputs.module_directories }}
    steps:
      - name: Get All Module Paths
        id: modulepaths
        shell: pwsh
        run: |
          $modulepaths = Get-ChildItem -Path .\src\modules\ -Directory
          $outpaths = $modulepaths.FullName -join ','
          echo "module_directories=$outpaths" >> $GITHUB_OUTPUT

  Publish:
    needs: SetUp
    uses: ntatschner/tatux_shared_workflows/.github/workflows/Publish_To_PSGallery.yml@main
    with:
      module_path: ${{ needs.SetUp.outputs.module_directories }}
    secrets:
      api_key: ${{ secrets.API_KEY }}